-- Insérer les 10 seniors avec une date d'adhésion de plus de 6 mois
INSERT INTO member (first_name, last_name, birth_date, gender, address, profession, phone_number, email, join_date,
                    registration_fee_paid, membership_dues_paid, admission_status)
VALUES ('Jean', 'Rakoto', '1985-03-15', 'MALE', 'Lot II 123 Antananarivo', 'Agriculteur', '341234567',
        'jean.rakoto@email.com', CURRENT_DATE - INTERVAL '200 days', TRUE, TRUE, 'APPROVED'),
       ('Marie', 'Razafy', '1990-07-22', 'FEMALE', 'Lot III 456 Antananarivo', 'Agricultrice', '342345678',
        'marie.razafy@email.com', CURRENT_DATE - INTERVAL '200 days', TRUE, TRUE, 'APPROVED'),
       ('Paul', 'Andriam', '1988-11-10', 'MALE', 'Lot IV 789 Antananarivo', 'Commerçant', '343456789',
        'paul.andriam@email.com', CURRENT_DATE - INTERVAL '200 days', TRUE, TRUE, 'APPROVED'),
       ('Sophie', 'Ranaivo', '1992-03-05', 'FEMALE', 'Lot V 012 Antananarivo', 'Ingénieur', '344567890',
        'sophie.ranaivo@email.com', CURRENT_DATE - INTERVAL '200 days', TRUE, TRUE, 'APPROVED'),
       ('Michel', 'Rakotomalala', '1975-12-20', 'MALE', 'Lot VI 345 Antananarivo', 'Agriculteur', '345678901',
        'michel.rakotomalala@email.com', CURRENT_DATE - INTERVAL '200 days', TRUE, TRUE, 'APPROVED'),
       ('Rija', 'Ramanantsoa', '1983-08-14', 'MALE', 'Lot XII 456 Antananarivo', 'Éleveur', '351234567',
        'rija.ramanantsoa@email.com', CURRENT_DATE - INTERVAL '200 days', TRUE, TRUE, 'APPROVED'),
       ('Lala', 'Rasolofo', '1987-02-28', 'FEMALE', 'Lot XIII 789 Antananarivo', 'Agricultrice', '352345678',
        'lala.rasolofo@email.com', CURRENT_DATE - INTERVAL '200 days', TRUE, TRUE, 'APPROVED'),
       ('Tovo', 'Randrianasolo', '1980-09-03', 'MALE', 'Lot XIV 012 Antananarivo', 'Pisciculteur', '353456789',
        'tovo.randrianasolo@email.com', CURRENT_DATE - INTERVAL '200 days', TRUE, TRUE, 'APPROVED'),
       ('Miora', 'Rakotozafy', '1986-11-25', 'FEMALE', 'Lot XV 345 Antananarivo', 'Commerçante', '354567890',
        'miora.rakotozafy@email.com', CURRENT_DATE - INTERVAL '200 days', TRUE, TRUE, 'APPROVED'),
       ('Fidy', 'Andriantsima', '1982-05-17', 'MALE', 'Lot XVI 678 Antananarivo', 'Technicien agricole', '355678901',
        'fidy.andriantsima@email.com', CURRENT_DATE - INTERVAL '200 days', TRUE, TRUE, 'APPROVED');